### DISCUSSION TITLE
FreeCAD 1.0.0.RC1 extremely slow on MacOS 14.5

### DISCUSSION THREAD

**Discussion by Cirenl** [FreeCAD/FreeCAD#16883] [Discussions that will turn in to issues but need refining]
I am not sure if it is just me, but I tried FreeCAD 1.0.0.RC1 on both LinuxMint 22 and MacOS 14.5. On Linux it runs great, but on MacOS it is extremely slow. Not workable at all. My impression is that it is a graphics problem. Does anybody else have the same experience? I also tried the weekly build, version 1.1.0dev, and also extemely slow.

**Comment by luzpaz** [comment]
More info, please add your full [About](https://wiki.freecad.org/About) info. Can you be less generic about what is slow specifically ?

**Comment by hacketiwack** [comment]
I'm facing the same issue on macOS 15.1.
What's especially slow are the panes like Task, Property, or the Explorer.

My version:

```yaml
OS: macOS 15.1.1
Architecture: arm64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```
