### ISSUE TITLE
[Materials][CAM] new Machinability requires coding changes for every Tool-Material & is missing Fz(chipload) data

### ISSUE THREAD

**Issue by spanner888** [FreeCAD/FreeCAD#16801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

new Machinability Materials will require coding changes for every Tool-Material & is missing Fz(chipload) data
The new Machinability Materials Model provides basis of calculating cutting RPM and power and includes a very coherent dataset and example calculations.

It includes data for two values to aid calculation of various cutting power calculations and two values of Vc, one each for Tool Material of HSS and Carbide.

Those two Tool materials are an excelent start for a generic tool based Speeds and Feeds calculations. However in future it is reasonable to expect at least the addition of tool coatings and no doubt requests to allow specific supplier Tools.

At present any changes to Tool materials, require changes to both the Machinability model, materials and any code that uses the associated values.

In addition current model is also missing fz (chipload) data.

The 'extended' machinability model proposed below suggests ways to solve both these issues and an alternate way to store the fz data, instead of just the raw value for each discrete value of Tool-Diameter.

Example code is buried within the just released CamScripts addon and includes a single example. See the README.md at https://github.com/spanner888/CamScripts

Proposed model
```
Model:
  Name: 'MachinabilityVcFzExtensions'
  UUID: 'b3aab784-ee76-4072-94b9-e028e27264be'
  URL: 'https://en.wikipedia.org/wiki/Speeds_and_feeds'
  Description: >-
    Model for calculating feeds and speeds on a milling machine or lathe
  Inherits:
    - Machinability:
      UUID: '9d81fcb2-bf81-48e3-bb57-d45ecf380096'
  DOI: ""
  Vc:
    Type: '2DArray'
    Columns:
      VcToolMat:
        Type: 'Quantity'
        Units: '1'
        URL: ''
        Description: "Index to tool Material list"
      SurfaceSpeed:
        Type: 'Quantity'
        Units: 'm/min'
        URL: ''
        Description: ""
    URL: ''
    Description: >
      2 Dimensional array SurfaceSpeed for each Tool Material
  Fz:
    Type: '2DArray'
    Columns:
      FzToolMat:
        Type: 'Quantity'
        Units: '1'
        URL: ''
        Description: "Index to tool Material list"
      fzSquared:
        Type: 'Quantity'
        Units: '1/mm'
        URL: ''
        Description: "x^2 curve var, can be zero for linear equation"
      fzSlope:
        Type: 'Quantity'
        Units: '1'
        URL: ''
        Description: "x^1 curve var"
      fzIntercept:
        Type: 'Quantity'
        Units: 'mm'
        URL: ''
        Description: "Y axis intercept"
    URL: ''
    Description: >
      Fz parameters for each Tool material
  ToolMat:
    Type: 'List'
    URL: ''
    Description: "List of Tool Material. Vc & Fz must be in same order to match data!"
```

Example Material Card:
```
---
# File created by FreeCAD 0.22.0 Revision: 38459 (Git)
General:
  UUID: "5043f450-2158-4aa7-ba22-59f0db62e391"
  Name: "AlCastAlloyINHERITED+fz"
  License: "All rights reserved"
Inherits:
  AluminumCastAlloy:
    UUID: "048ba0ec-1fc4-4e3c-9710-bde305a1503f"
Models:
  MachinabilityVcFzExtensions:
    UUID: 'b3aab784-ee76-4072-94b9-e028e27264be'
    Vc:
      - [["0", "80.00 m/min"],
        ["1", "120.00 m/min"],
        ["2", "31.00 m/min"]]
    # Fz Only row 0=HSS & row 1=Carbide has real data ATM
    Fz:
      - [["0", "-0.00020581", "0.00861056", "-0.03485845"],
        ["1", "-0.00024088", "0.00965887", "-0.037093"],
        ["2", "0.0", "0.0", "0.0"]]
    ToolMat:
      - "HSS"
      - "Carbide"
      - "HSS coated"
      - "Carbide coated"
      - "Ceramic"
```

Example output:
```
ToolBit: Test_JobUtils#_F_D6_4_L50_0_roughing_HRangles , has HelixAngle, using value: 17.2 deg
ToolBit: Test_JobUtils#_F_D6_4_L50_0_roughing_HRangles , has RakeAngle, using value: 29.9 deg
material : AlCastAlloyINHERITED+fz

mat inf:  Material/Machining/AlCastAlloyINHERITED+fz.FCMat 
	 Custom /home/spanner888/Documents/_APPS_lappy/FC_wkly-38827/appd_mlappy/Mod/CamScripts/freecad/cam_scripts/cutting_tool_data/Resources
parent inf: Machining/AluminumCastAlloy.FCMat System /tmp/.mount_FC_wklZxQ9tw/usr/share/Mod/Material/Resources/Materials
Vc array data [[0.0, 1333.3333333333335 mm/s], [1.0, 2000.0000000000002 mm/s], [2.0, 516.6666666666667 mm/s]]
Vc for Tool Mat: HSS  is:  1333.3333333333335 mm/s 1333.3333333333335 mm/s

Fz.Array data:
	 HSS [0.0, -0.00020581, 0.00861056, -0.03485845]
	 Carbide [1.0, -0.00024088, 0.00965887, -0.037093]
	 HSS coated [2.0, 0.0, 0.0, 0.0]
Calculated Fz for Tool Mat: HSS  is:  0.011819156400000003 mm

Calculated RPM = 3979
electrical spindle power  0.153 kW
Mc cutting torque 0.31204 Nm
vf  141 mm/min
mrr  45 mm^3/s
```

@jbaehr @sliptonic 

cc @davesrocketshop 

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38827 (Git) AppImage
Build type: Release
Branch: main
Hash: abd5c3ca31539f8ed37ac3dec2b9abd252a5310d
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * CamScripts
```

### Subproject(s) affected?

CAM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
