### ISSUE TITLE
Moving object in body causes cyclic dependencies

### ISSUE THREAD

**Issue by FreeCAD-Bug-Importer** [FreeCAD/FreeCAD#5892]
Issue imported from https://tracker.freecad.org/view.php?id=3888

* **Reporter:** wmayer
* **Date submitted:** 3/6/2019
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** confirmed
* **Tags:** 

# Original report text

When choosing the option to move an object at the beginning of the body a cyclic dependency will be created.

# Additional information

https://forum.freecadweb.org/viewtopic.php?f=3&t=34684

# Steps to reproduce

1. Create a body
2. Create a sketch and pad
3. Select a face, create new sketch and pad it
4. Select the second pad, call the function to move the object
5. Press OK to accept the default value

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **Updated:** 2/6/2021

**Comment by adrianinsaval** [comment]
in current version the operation is rejected
![image](https://github.com/FreeCAD/FreeCAD/assets/36372335/9dbe1878-19ae-4073-9bd5-c3336783a6f6)
```yml
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.0.33110 (Git)
Build type: Release
Branch: master
Hash: 18e40941ceb36c52701a7c74ea26043ef3385701
Python 3.10.10, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: C/Default (C) [ OS: Spanish/Paraguay (es_PY) ]
Installed mods: 
```
